version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: auralis-postgres
    environment:
      POSTGRES_DB: auralis_transcriptor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: auralis-backend
    environment:
      NODE_ENV: development
      PORT: 5000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/auralis_transcriptor
      JWT_SECRET: your-super-secret-jwt-key-for-development-only
      JWT_REFRESH_SECRET: your-refresh-secret-key-for-development-only
      FRONTEND_URL: http://localhost:3000
      # Ready-to-run local provider via python-services adapter:
      TRANSCRIPTION_PROVIDER: whispercpp
      WHISPERCPP_URL: http://python-services:8000/adapters/whispercpp
      # Alternatively enable Vosk adapter by setting:
      # TRANSCRIPTION_PROVIDER: vosk
      # VOSK_URL: http://python-services:8000/adapters/vosk
      LOG_LEVEL: debug
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/temp:/app/temp
      - ./backend/logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      python-services:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (res) =\u003e { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () =\u003e process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Frontend (Vite)
  frontend:
    build:
      context: ./frontend/auralis-transcriptor-frontend
      dockerfile: Dockerfile
      target: development
    container_name: auralis-frontend
    environment:
      VITE_API_URL: http://localhost:5000/api
      CHOKIDAR_USEPOLLING: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/auralis-transcriptor-frontend/src:/app/src
      - ./frontend/auralis-transcriptor-frontend/public:/app/public
      - /app/node_modules
    depends_on:
      - backend

  # Python services (ASR/TTS adapters and local pipelines)
  python-services:
    image: python:3.11-slim
    container_name: auralis-python-services
    working_dir: /app
    environment:
      - VOSK_MODEL=/models/vosk
      - WHISPER_MODEL=openai/whisper-base
      - PYTHONUNBUFFERED=1
    volumes:
      - ./python-services:/app
      - ./models:/models
    command: sh -c "pip install --no-cache-dir -r requirements.txt && uvicorn simple_audio_service:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
    depends_on:
      - backend

  # Redis (for future caching and session management)
  redis:
    image: redis:7-alpine
    container_name: auralis-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: auralis-network
